# Generated by Django 4.1.4 on 2022-12-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMeal', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeal', models.CharField(blank=True, max_length=1000, null=True)),
                ('strDrinkAlternate', models.CharField(blank=True, max_length=1000, null=True)),
                ('strCategory', models.CharField(blank=True, max_length=1000, null=True)),
                ('strArea', models.CharField(blank=True, max_length=1000, null=True)),
                ('strInstructions', models.CharField(blank=True, max_length=1000, null=True)),
                ('strTags', models.CharField(blank=True, max_length=1000, null=True)),
                ('strYoutube', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient1', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient2', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient3', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient4', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient5', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient6', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient7', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient8', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient9', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient10', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient11', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient12', models.CharField(blank=True, max_length=1000, null=True)),
                ('strIngredient13', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure1', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure2', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure3', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure4', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure5', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure6', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure7', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure8', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure9', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure10', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure11', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure12', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMeasure13', models.CharField(blank=True, max_length=1000, null=True)),
                ('strSource', models.CharField(blank=True, max_length=1000, null=True)),
                ('strImageSource', models.CharField(blank=True, max_length=1000, null=True)),
                ('strCreativeCommonsConfirmed', models.CharField(blank=True, max_length=1000, null=True)),
                ('dateModified', models.CharField(blank=True, max_length=1000, null=True)),
                ('strMealThumb', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
